Client/Client/Controllers/FridgesProductsController.cs
using Client.Models.FridgeProducts;
using Domain.Entities.FridgeProduct;
using Domain.Interfaces.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class FridgesProductsController : Controller
    {
        private readonly IServiceManager _serviceManager;

        public FridgesProductsController(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
        }

        public async Task<IActionResult> GetByFridgeId(Guid fridgeId)
        {
            var fridgeProductsViewModel = new FridgeProductViewModel()
            {
                FridgeProducts = await _serviceManager.FridgeProductService.GetFridgeProductsByFridgeIdAsync(fridgeId)
            };

            return View(fridgeProductsViewModel);
        }

        public IActionResult Update(FridgeProductForUpdateViewModel fridgeProductForUpdateViewModel)
        {
            return View("Update", fridgeProductForUpdateViewModel);
        }

        public IActionResult Delete(FridgeProductForDeleteViewModel fridgeProductForDeleteViewModel) => 
            PartialView("_DeletePartial", fridgeProductForDeleteViewModel);

        [HttpPost]
        [ActionName(nameof(DeleteProductFromFridgeByIdAsync))]
        public async Task<IActionResult> DeleteProductFromFridgeByIdAsync(Guid id)
        {
            await _serviceManager.FridgeProductService.DeleteProductFromFridgeByIdAsync(id);
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ActionName(nameof(UpdateFridgeProductAsync))]
        public async Task<IActionResult> UpdateFridgeProductAsync(FridgeProductForUpdateViewModel fridgeProductForUpdateViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("Update", fridgeProductForUpdateViewModel);
            }

            await _serviceManager.FridgeProductService.UpdateFridgeProductAsync(new FridgeProductForUpdate()
            {
                Id = fridgeProductForUpdateViewModel.Id,
                FridgeId = fridgeProductForUpdateViewModel.FridgeId,
                ProductId = fridgeProductForUpdateViewModel.ProductId,
                ProductQuantity = fridgeProductForUpdateViewModel.ProductQuantity
            });

            return RedirectToAction(nameof(GetByFridgeId), new { fridgeId = fridgeProductForUpdateViewModel.FridgeId });
        }
    }
}

Client/Client/Views/FridgesProducts/GetByFridgeId.cshtml
@model Client.Models.FridgeProducts.FridgeProductViewModel

@{
    ViewData["Title"] = "Fridge Products";
}

<div id="PlaceHolderHere"></div>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Fridge Product List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Add Product(s)
            </a>
        </div>
    </div>
    <br /><br />

    <table class="products-table table table-bordered table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayName("Name")
                </th>
                <th>
                    @Html.DisplayName("Quantity")
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.FridgeProducts)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(m => item.ProductName)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.ProductQuantity)
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            @using (@Html.BeginForm("Update", "FridgesProducts"))
                            {
                                @Html.Hidden("Id", item.Id)
                                @Html.Hidden("FridgeId", item.FridgeId)
                                @Html.Hidden("ProductId", item.ProductId)
                                @Html.Hidden("ProductQuantity", item.ProductQuantity)
                                <button type="submit" class="btn btn-warning mx-2"><i class="bi bi-pencil-square"></i>Update</button>
                            }
                            <form>
                                <button type="button" class="btn btn-danger mx-2" data-toggle="ajax-modal" data-target="#remove"
                                    data-url="@Url.Action($"Delete/{item.Id}")"><i class="bi bi-trash-fill"></i>Delete</button>
                            </form>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Client/Client/Views/FridgesProducts/Update.cshtml
@model Client.Models.FridgeProducts.FridgeProductForUpdateViewModel

@{
    ViewData["Title"] = "Update Fridge Product";
}

<form asp-action="UpdateFridgeProductAsync">
    <div class="border-light window p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Update Fridge Product</h2>
            <hr />
        </div>
        @Html.Hidden("Id", @Model.Id)
        @Html.Hidden("FridgeId", @Model.FridgeId)
        @Html.Hidden("ProductId", @Model.ProductId)
        <div class="mb-3">
            <label class="form-label">Product Quantity</label>
            <input asp-for="ProductQuantity" class="form-control" autocomplete="off" />
            <span asp-validation-for="ProductQuantity" class="text-danger"></span>
        </div>
       <div class="mt-4">
            <button type="submit" class="btn btn-success btn-lg">Update</button>
            <a asp-action="GetByFridgeId" asp-route-fridgeId="@Model.FridgeId" class="btn btn-danger btn-lg mx-2">Cancel</a>
       </div>
    </div>
</form>

Client/Client/Views/FridgesProducts/_DeletePartial.cshtml
@model Client.Models.FridgeProducts.FridgeProductForDeleteViewModel

@{
    Layout = "_PopUpPartial";
}

<div class="modal-body">
    @using (@Html.BeginForm("DeleteProductFromFridgeByIdAsync", "FridgesProducts"))
    {
        @Html.HiddenFor(m => @Model.Id)
        <div class="form-group">
            <span>Are you sure you'd like to delete this product from the fridge? This action cannot be undone</span>
        </div>
    }
</div>