Client/Client/Controllers/FridgesController.cs
using Client.Models.Fridges;
using Domain.Entities.FridgeProduct;
using Domain.Entities.Fridges;
using Domain.Interfaces.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class FridgesController : Controller
    {
        private readonly IServiceManager _serviceManager;

        public FridgesController(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
        }

        public async Task<IActionResult> Index()
        {
            var fridges = new FridgesViewModel
            {
                Fridges = await _serviceManager.FridgeService.GetAllFridgesAsync()
            };

            return View(fridges);
        }

        public IActionResult Delete(FridgeForDeleteViewModel fridgeForDeleteViewModel) => PartialView("_DeletePartial", fridgeForDeleteViewModel);

        public async Task<IActionResult> Create()
        {
            var models = await _serviceManager.FridgeModelService.GetAllFridgeModelsAsync();
            SelectList modelsList = new SelectList(models, "Id", "Name");

            var products = await _serviceManager.ProductService.GetAllProductsAsync();
            var fridgeForCreationViewModel = new FridgeForCreationViewModel()
            {
                Products = new MultiSelectList(products, "Id", "Name"),
            };

            ViewBag.Models = modelsList;
            return View("Create", fridgeForCreationViewModel);
        }

        public async Task<IActionResult> Update(FridgeForUpdateViewModel fridgeForUpdateViewModel)
        {
            var models = await _serviceManager.FridgeModelService.GetAllFridgeModelsAsync();
            SelectList modelsList = new SelectList(models, "Id", "Name");

            ViewBag.Models = modelsList;
            return View("Update", fridgeForUpdateViewModel);
        }

        [HttpPost]
        [ActionName(nameof(CreateFridgeAsync))]
        public async Task<IActionResult> CreateFridgeAsync(FridgeForCreationViewModel fridgeForCreationViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", fridgeForCreationViewModel);
            }

            var createdFridge = await _serviceManager.FridgeService.CreateFridgeAsync(new FridgeForCreation()
            {
                FridgeModelId = fridgeForCreationViewModel.FridgeModelId,
                OwnerName = fridgeForCreationViewModel?.OwnerName,
                Description = fridgeForCreationViewModel?.Description,
            });

            var products = await _serviceManager.ProductService.GetAllProductsAsync();

            if (fridgeForCreationViewModel.ProductIds != null){
                 var prodcutsToAdd = (from product in products
                                     from id in fridgeForCreationViewModel?.ProductIds
                                     where product.Id == id
                                     select new FridgeProductForCreation
                                     {
                                         FridgeId = createdFridge.Id,
                                         ProductId = id,
                                         ProductQuantity = product.Quantity
                                     }).ToList();
                await _serviceManager.FridgeProductService.AddProductsIntoFridgeAsync(prodcutsToAdd);
            }


            return RedirectToAction("Index");
        }

        [HttpPost]
        [ActionName(nameof(UpdateFridgeAsync))]
        public async Task<IActionResult> UpdateFridgeAsync(FridgeForUpdateViewModel fridgeForUpdateViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("Update", fridgeForUpdateViewModel);
            }

            await _serviceManager.FridgeService.UpdateFridgeAsync(new FridgeForUpdate()
            {
                Id = fridgeForUpdateViewModel.Id,
                FridgeModelId = fridgeForUpdateViewModel.FridgeModelId,
                OwnerName = fridgeForUpdateViewModel?.OwnerName,
                Description = fridgeForUpdateViewModel?.Description
            });

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ActionName(nameof(DeleteFridgeAsync))]
        public async Task<IActionResult> DeleteFridgeAsync(Guid id)
        {
            await _serviceManager.FridgeService.DeleteFridgeAsync(id);
            return RedirectToAction("Index");
        }
    }
}

Client/Client/Controllers/ProductsController.cs
using Client.Models.Products;
using Domain.Entities.Products;
using Domain.Interfaces.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IServiceManager _serviceManager;

        public ProductsController(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
        }

        public async Task<IActionResult> Index()
        {
            var products = new ProductsViewModel
            {
                Products = await _serviceManager.ProductService.GetAllProductsAsync()
            };

            return View(products);
        }

        public IActionResult Create() => View("Create", new ProductForCreationViewModel());

        public IActionResult Update(ProductForUpdateViewModel productForUpdateViewModel) => View("Update", productForUpdateViewModel);

        public IActionResult Delete(ProductForDeleteViewModel productForDeleteViewModel) => PartialView("_DeletePartial", productForDeleteViewModel);

        [HttpPost]
        [ActionName(nameof(CreateProductAsync))]
        public async Task<IActionResult> CreateProductAsync(ProductForCreationViewModel productForCreationViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", productForCreationViewModel);
            }

            await _serviceManager.ProductService.CreateProductAsync(new ProductForCreation()
            {
                Name = productForCreationViewModel.Name,
                Quantity = productForCreationViewModel.Quantity,
            });

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ActionName(nameof(DeleteProductAsync))]
        public async Task<IActionResult> DeleteProductAsync(Guid id)
        {
            await _serviceManager.ProductService.DeleteProductAsync(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ActionName(nameof(UpdateProductAsync))]
        public async Task<IActionResult> UpdateProductAsync(ProductForUpdateViewModel productForUpdateViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("Update", productForUpdateViewModel);
            }

            await _serviceManager.ProductService.UpdateProductAsync(new ProductForUpdate()
            {
                Id = productForUpdateViewModel.Id,
                Name = productForUpdateViewModel.Name,
                Quantity = productForUpdateViewModel.Quantity
            });

            return RedirectToAction("Index");
        }
    }
}

Client/Client/Controllers/UserManagementController.cs
using Client.Models.Users;
using Domain.Common;
using Domain.Interfaces.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class UserManagementController : Controller
    {
        private readonly IServiceManager _serviceManager;

        public UserManagementController(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
        }

        public ViewResult Index()
        {
            return View();
        }

        public ViewResult SignUp()
        {
            return View("SignUp", new SignUpViewModel());
        }

        [HttpPost]
        [ActionName(nameof(SignUpPostAsync))]
        public async Task<IActionResult> SignUpPostAsync(SignUpViewModel signUpViewModel)
        {
            if (!ModelState.IsValid)
                return View("SignUp", signUpViewModel);

            await _serviceManager.UserManagementService.SignUpAsync(signUpViewModel.Name, signUpViewModel.Surname, signUpViewModel.UserName,
                                                signUpViewModel.Password, signUpViewModel.Email);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ActionName(nameof(SignInPostAsync))]
        public async Task<IActionResult> SignInPostAsync(SignInViewModel signInViewModel)
        {
            if (!ModelState.IsValid)
                return View("Index", signInViewModel);

            var token = await _serviceManager.UserManagementService.LoginAsync(signInViewModel.UserName, signInViewModel.Password);

            Response.Cookies.Append(Constants.XAccessToken, token.Token, new CookieOptions()
            {
                HttpOnly = true,
                SameSite = SameSiteMode.Strict
            });

            return RedirectToAction("Index", "Home");
        }
    }
}

Client/Client/Views/Shared/_Init.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/styles.css" />
</head>         
<body>
    <div class="container p-5">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Client - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Client/Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Fridge Manager - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/cyberpunkTheme.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/form.css" />
</head>
<body>
    <header>
        @await Html.PartialAsync("_NavBar")
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Fridge Manager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Client/Client/Views/Shared/_NavBar.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor03">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                     <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-controller="Fridges" asp-action="Index">Fridges</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-controller="Products" asp-action="Index">Products</a>
                </li>
            </ul>
            <form class="d-flex">
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="UserManagement" asp-action="Index">Sign in</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="UserManagement" asp-action="SignUp">Sign up</a>
                        </li>
                    </ul>
                </div>
            </form>
        </div>
    </div>
</nav>

Client/Client/Views/Shared/_PopUpPartial.cshtml
<div class="modal fade" id="remove">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Action confirmation</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"></span>
                </button>
            </div>
            <div class="modal-body">
                @RenderBody()
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-save="modal">Confirm</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>